# Cargo build configuration

[target.x86_64-unknown-linux-musl]
# Use vendored OpenSSL for static musl builds
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# Vendor OpenSSL for musl builds to avoid dynamic linking issues
OPENSSL_STATIC = "1"
